/*
This function is created by: Asger Geel Weirsøe for use only in the P1-Project.
The function creates a document that writes the data used to generate a school schedule.


Date:           9/11
Version:        2.00
*/

int DaysWhereTeacherIsAbcent(int *teacherDaysData, char teacherFirstName, char teacherLastName, int numOfTeachers){
     #if defined(_WIN32)
    _mkdir("./data");
     #else 
    mkdir("./data", 0700); 
     #endif   
    int i,k=0;
    FILE *fptr;

    if ((fptr=fopen("data/TeacherIsAbcent.txt","r"))==NULL){
        
        printf("Did not find file, creating new\n");
        fptr = fopen("data/TeacherIsAbcent.txt", "w"); 
        fputs("//This entire document is dedicated to the processing of a school schedule.\n",fptr);
        fputs("//Please do not edit this file for any reasons. Unless you know what you are doing.\n\n",fptr);
        fputs("//For the teachers, there will be data that tells what classes they can participate in,\n",fptr);
        fputs("//0 = they cannot participate, 1 = they can participate \n\n",fptr);
        fputs("//The following data will represent: \n",fptr);
        fputs("//Unique ID:     ID:\n",fptr);
        fputs("//Name:          Name:\n",fptr);
        fputs("//Days:          Day:",fptr);

        fputs("--------ALL TEACHERS--------\n",fptr);
        for(i = 0;i<numOfTeachers;i++){
            fputs("--Teacher Start--\n",fptr);
            fprintf(fptr, "Teacher Nr: %i\n",i );
            ffprintf(fptr, "ID: %s %s\n",teacherDaysData.ID[i] );
            fprintf(fptr, "Name: %s %s\n",teacherFirstName,teacherLastName );
            for(; i<teacherDaysData.numOfDays[i];k++){
                fprintf(fptr, "Day: %s\n",teacherDaysData.day[k]);
            }
            fputs("--Teacher End--\n\n",fptr);
        }
    }
        
        fclose(fptr);
    return 0;
}
