/*
This function is created by: Asger Geel Weirsøe for use only in the P1-Project.
The function creates a document that writes the data used to generate a school schedule.


Date:           9/11
Version:        1.05
*/

int StudentData(Data_elever_t /*->array with students<-*/[]){
    #if defined(_WIN32)     /* den tjekker om det er windows til at lave en folder */
        _mkdir("./data");
    #else                   /* laver en en text fil i linux */
        mkdir("./data", 0700); 
    #endif     

    int i;
    FILE *fptr; /* filpointer */

    if ((fptr=fopen("data/StudentData.txt","r"))==NULL){    /*  */
        printf("Did not find file, creating new\n");
        fptr = fopen("data/StudentData.txt", "w"); 
        fputs("//This entire document is dedicated to the processing of a school schedule.\n",fptr);
        fputs("//Please do not edit this file for any reasons. Unless you know what you are doing.\n\n",fptr);
        fputs("//The following data will represent: \n",fptr);
        fputs("//Unique ID:                 ID:\n",fptr);
        fputs("//Name:                      Name:\n",fptr);
        fputs("//Mundtlig Matematik:        Mm:\n",fptr);
        fputs("//Skriftlig Matematik:       Sm:\n",fptr);
        fputs("//Mundtlig Dansk:            Md:\n",fptr);
        fputs("//Skriftlig Dansk:           Sd:\n",fptr);
        fputs("//Mundtlig Fysik:            Mf:\n",fptr);
        fputs("//Skriftlig Fysik:           Sf:\n",fptr);
        fputs("//Mundtlig Engelsk:          Me:\n",fptr);
        fputs("//Skriftlig Engelsk:         Se:\n",fptr);
        fputs("//Mundtlig Kemi:             Mk:\n",fptr);
        fputs("//Skriftlig Kemi:            Sk:\n",fptr);
        fputs("//Mundtlig Teknologi:        Mt:\n",fptr);
        fputs("//Mundtlig Programmering:    Mp:\n",fptr);
        fputs("//Mundtlig Idéhistorie:      Mi:\n",fptr);
        fputs("//Mundtlig Biologi:          Mb:\n",fptr);
        fputs("//Mundtlig kom/it:           Mki:\n",fptr);
        fputs("//Mundtlig Samfundsfag:      Ms:\n\n\n\n",fptr);

        fputs("-------------ALL STUDENTS--------------\n",fptr);

        for(i = 0;i<numOfStudents;i++){
            fputs("--Student start--\n",fptr);
            fprintf(fptr, "Student nr: %i\n",i );
            fprintf(fptr,"ID: %i\n",/*->array with students<-*/[i]->unikID);
            fprintf(fptr, "Name: %s %s\n",/*->array with students<-*/[i]->elev_for_navn,/*->array with students<-*/[i]->elev_efternavn );
            fprintf(fptr,"Mm: %i\n",/*->array with students<-*/[i]->Mm);
            fprintf(fptr,"Sm: %i\n",/*->array with students<-*/[i]->Sm);
            fprintf(fptr,"Md: %i\n",/*->array with students<-*/[i]->Md);
            fprintf(fptr,"Sd: %i\n",/*->array with students<-*/[i]->Sd);
            fprintf(fptr,"Mf: %i\n",/*->array with students<-*/[i]->Mf);
            fprintf(fptr,"Sf: %i\n",/*->array with students<-*/[i]->Sf);
            fprintf(fptr,"Me: %i\n",/*->array with students<-*/[i]->Me);
            fprintf(fptr,"Se: %i\n",/*->array with students<-*/[i]->Se);
            fprintf(fptr,"Mk: %i\n",/*->array with students<-*/[i]->Mk);
            fprintf(fptr,"Sk: %i\n",/*->array with students<-*/[i]->Sk);
            fprintf(fptr,"Mt: %i\n",/*->array with students<-*/[i]->Mt);
            fprintf(fptr,"Mp: %i\n",/*->array with students<-*/[i]->Mp);
            fprintf(fptr,"Mi: %i\n",/*->array with students<-*/[i]->Mi);
            fprintf(fptr,"Mb: %i\n",/*->array with students<-*/[i]->Mb);
            fprintf(fptr,"Mki: %i\n",/*->array with students<-*/[i]->Mki);
            fprintf(fptr,"Ms: %i\n",/*->array with students<-*/[i]->Ms);
            fputs("--Student end--\n\n",fptr);
        }
    }
    
    fclose(fptr);

    return (0);
}
