/*
This function is created by: Asger Geel Weirsøe for use only in the P1-Project.
The function creates a document that writes the data used to generate a school schedule.


Date:           8/11
Version:        1.02
*/

#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <stdio.h>

  


int TeacherData(int *teacherData, char teacherFirstName, char teacherLastName, int numOfTeachers){
    #if defined(_WIN32)
    _mkdir("./data");
     #else 
    mkdir("./data", 0700); 
     #endif
    int i;
    FILE *fptr;

    if ((fptr=fopen("data/TeacherData.txt","r"))==NULL){
        
        printf("Did not find file, creating new\n");
        fptr = fopen("data/TeacherData.txt", "w"); 
        fputs("//This entire document is dedicated to the processing of a school schedule.\n",fptr);
        fputs("//Please do not edit this file for any reasons. Unless you know what you are doing.\n\n",fptr);
        fputs("//For the teachers, there will be data that tells what classes they can participate in,\n",fptr);
        fputs("//0 = they can not participate, 1 = they can be an replacement & 2 = they can do the class fully\n\n");
        fputs("//The following data will represent: \n",fptr);
        fputs("//Unique ID:                 ID:\n",fptr);
        fputs("//Name:                      Name:\n",fptr);
        fputs("//Mundtlig Matematik:        Mm:\n",fptr);
        fputs("//Skriftlig Matematik:       Sm:\n",fptr);
        fputs("//Mundtlig Dansk:            Md:\n",fptr);
        fputs("//Skriftlig Dansk:           Sd:\n",fptr);
        fputs("//Mundtlig Fysik:            Mf:\n",fptr);
        fputs("//Skriftlig Fysik:           Sf:\n",fptr);
        fputs("//Mundtlig Engelsk:          Me:\n",fptr);
        fputs("//Skriftlig Engelsk:         Se:\n",fptr);
        fputs("//Mundtlig Kemi:             Mk:\n",fptr);
        fputs("//Skriftlig Kemi:            Sk:\n",fptr);
        fputs("//Mundtlig Teknologi:        Mt:\n",fptr);
        fputs("//Mundtlig Programmering:    Mp:\n",fptr);
        fputs("//Mundtlig Idéhistorie:      Mi:\n",fptr);
        fputs("//Mundtlig Biologi:          Mb:\n",fptr);
        fputs("//Mundtlig kom/it:           Mki:\n",fptr);
        fputs("//Mundtlig Samfundsfag:      Ms:\n\n\n\n",fptr);

        fputs("--------ALL TEACHERS--------\n",fptr);
        for(i = 0;i<numOfTeachers;i++){
            fputs("--Teacher Start--\n",fptr);
            fprintf(fptr, "Teacher nr: %i\n",i );
            fprintf(fptr,"ID: %i\n",teacherData[0]);
            fprintf(fptr, "Name: %s %s\n",teacherFirstName,teacherLastName );
            fprintf(fptr,"Mm: %i\n",teacherData[1]);
            fprintf(fptr,"Sm: %i\n",teacherData[2]);
            fprintf(fptr,"Md: %i\n",teacherData[3]);
            fprintf(fptr,"Sd: %i\n",teacherData[4]);
            fprintf(fptr,"Mf: %i\n",teacherData[5]);
            fprintf(fptr,"Sf: %i\n",teacherData[6]);
            fprintf(fptr,"Me: %i\n",teacherData[7]);
            fprintf(fptr,"Se: %i\n",teacherData[8]);
            fprintf(fptr,"Mk: %i\n",teacherData[9]);
            fprintf(fptr,"Sk: %i\n",teacherData[10]);
            fprintf(fptr,"Mt: %i\n",teacherData[11]);
            fprintf(fptr,"Mp: %i\n",teacherData[12]);
            fprintf(fptr,"Mi: %i\n",teacherData[13]);
            fprintf(fptr,"Mb: %i\n",teacherData[14]);
            fprintf(fptr,"Mki: %i\n",teacherData[15]);
            fprintf(fptr,"Ms: %i\n",teacherData[16]);
            fputs("--Teacher End--\n\n",fptr);
        }
    }
        
        fclose(fptr);
    return 0;
}
