/*
This function is created by: Asger Geel Weirsøe for use only in the P1-Project.
The function creates a document that writes the data used to generate a school schedule.


Date:           9/11
Version:        1.04
*/
void Write_File_For_Teachers(Subject_t subjects_data[], int numberOfClasses, FILE *fptr);

int TeacherData(Subject_t subjects_data[], int numberOfClasses){
    FILE *fptr;
    char yes_or_no;
    #if defined(_WIN32)
        _mkdir("./data");
     #else 
        mkdir("./data", 0700); 
     #endif

    

    while(1) {
        if ((fptr=fopen("data/TeacherData.txt","r"))==NULL){    /*  */

        Write_File_For_Teachers(subjects_data,numberOfClasses,fptr);

        } else {

            printf("File already exists, do you want to override it? [Y]es / [N]o\n");
            scanf("%c",&yes_or_no);

            if(yes_or_no == 'N') {

                printf("File not overridden\n");
                break;
            }else if(yes_or_no == 'Y') {

                printf("Deleting file.\n");
                Write_File_For_Teachers(subjects_data,numberOfClasses,fptr);
                printf("New file created.\n");
                break;
            }else {

                printf("ERROR: indput incorrect.\n");
            
            }
        } 
    }
        
    fclose(fptr);

    return (0);
}

void Write_File_For_Teachers(Subject_t subjects_data[], int numberOfClasses, FILE *fptr) {
    int k;
    printf("Did not find file, creating new\n");
        fptr = fopen("data/TeacherData.txt", "w"); 
        fputs("//This entire document is dedicated to the processing of a school schedule.\n",fptr);
        fputs("//Please do not edit this file for any reasons. Unless you know what you are doing.\n\n",fptr);

        fputs("------------SUBJECT START------------\n",fptr);
        for(k = 0; k < numberOfClasses; k++) {

            fputs("--Subject Start--\n\n",fptr);
            fprintf(fptr, "Examen: %s\n\n",subjects_data[k].subject);

            fputs("--Teacher Start--\n",fptr);
            fprintf(fptr,"Teacher unik ID: %i\n",subjects_data[k].teacher.ID);
            fprintf(fptr, "First name: %s \n",subjects_data[k].teacher.name);
            fprintf(fptr, "Last name: %s\n",subjects_data[k].teacher.surname);
            fputs("--Teacher End--\n\n",fptr);

            fputs("--Censor Start--\n",fptr);
            fprintf(fptr, "Censor unik ID: %i\n",subjects_data[k].censor.ID);
            fprintf(fptr, "First name: %s\n",subjects_data[k].censor.name);
            fprintf(fptr, "Last name: %s\n",subjects_data[k].censor.surname);
            fputs("--Censor End--\n\n",fptr);
            
        }

        
}
