/*
This function is created by: Asger Geel Weirsøe for use only in the P1-Project.
The function creates a document that writes the data used to generate a school schedule.


Date:           9/11
Version:        1.04
*/

int TeacherData(Data_laerer_t /*->array with teachers<-*/[], char teacherFirstName, char teacherLastName, int numOfTeachers){
    #if defined(_WIN32)
        _mkdir("./data");
     #else 
        mkdir("./data", 0700); 
     #endif

    int i;
    FILE *fptr;

    if ((fptr=fopen("data/TeacherData.txt","r"))==NULL){ /* hvis at filen ikke er lavet */
        printf("Did not find file, creating new\n");
        fptr = fopen("data/TeacherData.txt", "w"); 
        fputs("//This entire document is dedicated to the processing of a school schedule.\n",fptr);
        fputs("//Please do not edit this file for any reasons. Unless you know what you are doing.\n\n",fptr);
        fputs("//For the teachers, there will be data that tells what classes they can participate in,\n",fptr);
        fputs("//0 = they can not participate, 1 = they can be an replacement & 2 = they can do the class fully\n\n",fptr);
        fputs("//The following data will represent: \n",fptr);
        fputs("//Unique ID:                 ID:\n",fptr);
        fputs("//Name:                      Name:\n",fptr);
        fputs("//Mundtlig Matematik:        Mm:\n",fptr);
        fputs("//Skriftlig Matematik:       Sm:\n",fptr);
        fputs("//Mundtlig Dansk:            Md:\n",fptr);
        fputs("//Skriftlig Dansk:           Sd:\n",fptr);
        fputs("//Mundtlig Fysik:            Mf:\n",fptr);
        fputs("//Skriftlig Fysik:           Sf:\n",fptr);
        fputs("//Mundtlig Engelsk:          Me:\n",fptr);
        fputs("//Skriftlig Engelsk:         Se:\n",fptr);
        fputs("//Mundtlig Kemi:             Mk:\n",fptr);
        fputs("//Skriftlig Kemi:            Sk:\n",fptr);
        fputs("//Mundtlig Teknologi:        Mt:\n",fptr);
        fputs("//Mundtlig Programmering:    Mp:\n",fptr);
        fputs("//Mundtlig Idéhistorie:      Mi:\n",fptr);
        fputs("//Mundtlig Biologi:          Mb:\n",fptr);
        fputs("//Mundtlig kom/it:           Mki:\n",fptr);
        fputs("//Mundtlig Samfundsfag:      Ms:\n\n\n\n",fptr);

        fputs("------------ALL TEACHERS------------\n",fptr);
        for(i = 0;i<numOfTeachers;i++){
            fputs("--Teacher Start--\n",fptr);
            fprintf(fptr, "Teacher nr: %i\n",i );
            fprintf(fptr,"ID: %i\n",/*->array with teachers<-*/.unikID[i]);
            fprintf(fptr, "Name: %s %s\n",laerer_for_navn,laerer_efternavn );
            fprintf(fptr,"Mm: %i\n",/*->array with teachers<-*/[i].Mm);
            fprintf(fptr,"Sm: %i\n",/*->array with teachers<-*/[i].Sm);
            fprintf(fptr,"Md: %i\n",/*->array with teachers<-*/[i].Md);
            fprintf(fptr,"Sd: %i\n",/*->array with teachers<-*/[i].Sd);
            fprintf(fptr,"Mf: %i\n",/*->array with teachers<-*/[i].Mf);
            fprintf(fptr,"Sf: %i\n",/*->array with teachers<-*/[i].Sf);
            fprintf(fptr,"Me: %i\n",/*->array with teachers<-*/[i].Me);
            fprintf(fptr,"Se: %i\n",/*->array with teachers<-*/[i].Se);
            fprintf(fptr,"Mk: %i\n",/*->array with teachers<-*/[i].Mk);
            fprintf(fptr,"Sk: %i\n",/*->array with teachers<-*/[i].Sk);
            fprintf(fptr,"Mt: %i\n",/*->array with teachers<-*/[i].Mt);
            fprintf(fptr,"Mp: %i\n",/*->array with teachers<-*/[i].Mp);
            fprintf(fptr,"Mi: %i\n",/*->array with teachers<-*/[i].Mi);
            fprintf(fptr,"Mb: %i\n",/*->array with teachers<-*/[i].Mb);
            fprintf(fptr,"Mki: %i\n",/*->array with teachers<-*/[i].Mki);
            fprintf(fptr,"Ms: %i\n",/*->array with teachers<-*/[i].Ms);
            fputs("--Teacher End--\n\n",fptr);
        }
    }
        
    fclose(fptr);

    return (0);
}
